version: '2.2'
services:
  server1:
    image: mysimplekv:v1
    container_name: server1
    environment:
    - TZ=Asia/Shanghai
    network_mode: host
    command:
    - "--port"
    - "9527"
    - "--all-ports"
    - "9527"
    - "9528"
    - "9529"

  server2:
    image: mysimplekv:v1
    container_name: server2
    environment:
    - TZ=Asia/Shanghai
    network_mode: host
    command:
    - "--port"
    - "9528"
    - "--all-ports"
    - "9527"
    - "9528"
    - "9529"

  server3:
    image: mysimplekv:v1
    container_name: server3
    environment:
    - TZ=Asia/Shanghai
    network_mode: host
    command:
    - "--port"
    - "9529"
    - "--all-ports"
    - "9527"
    - "9528"
    - "9529"